##### 🎨 COLOR PALETTE #####
set -g @c_bg "#15141b"
set -g @c_fg "#edecee"
set -g @c_dim "#6d6d6d"
set -g @c_border "#29263c"
set -g @c_purple "#a277ff"
set -g @c_cyan "#82e2ff"
set -g @c_mint "#61ffca"
set -g @c_pink "#f694ff"

##### 🧠 TITLES #####
set -g set-titles on
set -g set-titles-string "#T"

##### 📜 MESSAGES & MODES #####
set -g mode-style "fg=#{@c_fg},bg=#{@c_purple}"
set -g message-style "fg=#{@c_bg},bg=#{@c_mint}"
set -g message-command-style "fg=#{@c_bg},bg=#{@c_mint}"

##### 🪟 PANES #####
set -g pane-border-style "fg=#{@c_border}"
set -g pane-active-border-style "fg=#{@c_purple}"

##### 📟 STATUS BAR #####
set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-style "fg=#{@c_fg},bg=#{@c_bg}"
set -g status-left-length 100
set -g status-right-length 100

##### ⬅️ LEFT SIDE #####
set -g status-left "#[fg=#{@c_bg},bg=#{@c_purple},bold] #S:#I.#P \
#[fg=#{@c_purple},bg=#{@c_cyan}]#[fg=#{@c_bg},bg=#{@c_cyan},bold] #(whoami) \
#[fg=#{@c_cyan},bg=#{@c_bg}]"

##### ➡️ RIGHT SIDE #####
set -g status-right "#{pomodoro_status} \
#[fg=#{@c_pink},bg=#{@c_bg}]#[fg=#{@c_purple},bg=#{@c_pink}]\
#[fg=#{@c_cyan},bg=#{@c_purple}]#[fg=#{@c_bg},bg=#{@c_cyan},bold] #h "

##### 🪞 WINDOW STATUS #####
# Inactive
set -g window-status-format "#[fg=#{@c_dim},bg=#{@c_bg}] #I  #{window_name} "

# Active
set -g window-status-current-format "#[fg=#{@c_bg},bg=#{@c_purple}]#[fg=#{@c_mint},bg=#{@c_purple},bold] #I \
#[fg=#{@c_purple},bg=#{@c_mint}] #{window_name} #[fg=#{@c_mint},bg=#{@c_bg}]"

# Activity indicator
set -g window-status-activity-style "underscore,fg=#{@c_pink},bg=#{@c_bg}"

##### ✨ SEPARATORS #####
set -g window-status-separator ""
