set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-ghostty:RGB"
set -as terminal-features ",*:RGB"

set -g extended-keys on
set -g extended-keys-format csi-u

# action key
set -g repeat-time 0
set -g focus-events on
set -g mouse on

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

#### basic settings
set -g status-justify "left"
set-window-option -g mode-keys vi
# import

source ~/.config/tmux/keybindings.conf
source ~/.config/tmux/theme.conf
source ~/.config/tmux/utility.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @pomodoro_pause " ⏸︎ "
set -g @pomodoro_complete " ✔︎ "
set -g @pomodoro_skip '"'
set -g @pomodoro_toggle "'"
set -g @pomodoro_notifications 'on'
set -g @pomodoro_granularity 'on'

set -g allow-passthrough on
set -g visual-activity off

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Overrides for tmux-sensible
set -g history-limit 64096
set -sg escape-time 10
