# Display lazygit
bind -r g display-popup -d '#{pane_current_path}' -w90% -h90% -E lazygit
# Display yazi
# bind -r y display-popup -d '#{pane_current_path}' -w90% -h90% -E 'tmux new-session yazi \; set status off'
# Open note
bind -r N display-popup -w80% -h80% -E 'nvim -c ObsidianToday'
