live_config_reload = true

[shell]
program = "fish"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"
decorations = 'Buttonless'

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

# Default colors
[colors.primary]
background = '#000b1e'
foreground = '#0abdc6'

[colors.cursor]
text = '#000b1e'
cursor = '#0abdc6'

# Normal colors
[colors.normal]
black = '#123e7c'
red = '#ff0000'
green = '#d300c4'
yellow = '#f57800'
blue = '#ffffff'
magenta = '#711c91'
cyan = '#0abdc6'
white = '#d7d7d5'

# Bright colors
[colors.bright]
black = '#1c61c2'
red = '#ff0000'
green = '#d300c4'
yellow = '#f57800'
blue = '#00ff00'
magenta = '#711c91'
cyan = '#0abdc6'
white = '#d7d7d5'
